<option value="Abaco">Abaco</option>
<option value="Acklins">Acklins</option>
<option value="Andros">Andros</option>
<option value="Berry Islands">Berry Islands</option>
<option value="Bimini">Bimini</option>
<option value="Cat Island">Cat Island</option>
<option value="Crooked Island">Crooked Island</option>
<option value="Eleuthera">Eleuthera</option>
<option value="Exuma">Exuma</option>
<option value="Grand Bahama">Grand Bahama</option>
<option value="Inagua">Inagua</option>
<option value="Long Cay">Long Cay</option>
<option value="Long Island">Long Island</option>
<option value="Mayaguana">Mayaguana</option>
<option value="New Providence">New Providence</option>
<option value="Ragged Island">Ragged Island</option>
<option value="Rum Cay">Rum Cay</option>
<option value="San Salvador">San Salvador</option>
